name: Test
on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-jammy
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Deduplicate dependencies
        run: yarn run yarn-deduplicate --fail --strategy fewer
      - name: Build
        run: yarn run build
      - name: Format
        run: yarn run prettier --check
      - name: Lint
        run: yarn run xo
      - name: Run Action
        uses: ./
        if: always()
        with:
          app_id: 9999999
          private_key: ""